### PR TITLE
Add test for fromV1

### PR DESCRIPTION
**Pull request by chikeichan**
Relates to #26 

Adding a few missing negative tests. Much of the remaining missing coverage seem to be from the `_typeof` polyfills.

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi Jacky,
sorry that this never got merged. Would it be ok if I take the code parts with the tests of your PR manually and integrate into the updates TypeScript test files? Or would you alternatively even have some time to update the PR?

Hope everything is fine, all the best
Holger

**Comment by holgerd77** [comment]
Hi @chikeichan, would really be happy on an answer here 😀  (see comment above), otherwise I would need to close which would be a bit a pity.

All the best
Holger

**Comment by holgerd77** [comment]
(I know it is an absurdly late reaction here, but from the current PoV this is the only thing I can do)

**Comment by chikeichan** [comment]
> Hi Jacky,
> sorry that this never got merged. Would it be ok if I take the code parts with the tests of your PR manually and integrate into the updates TypeScript test files? Or would you alternatively even have some time to update the PR?
> 
> Hope everything is fine, all the best
> Holger

Hi @holgerd77 - hope all is well! please fell free to take the code parts with the tests and integrate. Cheers!

**Pull request closed without merging**
