### PR TITLE
Add changelog for 0.6.3

### LINKED ISSUE #69: New minor release v0.6.3
@axic Are you ok with a new minor release with the latest merges/changes?

### PR DESCRIPTION
**Pull request by axic**
Closes #69.

### CODE REVIEW

**Comment by axic** [comment]
Not sure how to do that version bump in this PR since it also requires a tag..

**Comment by holgerd77** [comment]
Just in package.json

**Comment by holgerd77** [comment]
Tag is done on GitHub release page

**Comment by holgerd77** [comment]
Follow-up note: with a new release version bump in `package.json` all code changes in the repository are included, otherwise this would require an additional PR just for this tiny change. If you can do a short update, wen can do some release on this before Christmas, would be good since somewhat overdue.

**Comment by axic** [comment]
> additional PR just for this tiny change.

Usually we've just pushed that.

**Comment by axic** [comment]
@holgerd77 added the version bump

**Comment by holgerd77** [comment]
> > additional PR just for this tiny change.
> 
> Usually we've just pushed that.

How can you just push, isn't the ``master`` branch protected?

**Comment by axic** [comment]
> > > additional PR just for this tiny change.
> > 
> > Usually we've just pushed that.
> 
> How can you just push, isn't the ``master`` branch protected?

Depends, mostly it is protected from force pushes only, unless you tick the "enforce rules on administrators" too.

**Comment by holgerd77** [comment]
Will directly do the release.

**Comment by holgerd77** [comment]
Ah, or will you? Will wait, don't mind but we should actually synchronize. 😄

**Comment by holgerd77** [comment]
Ah ok, have seen that you have also published on `npm`.

**Comment by axic** [comment]
Yeah sorry wanted to be done with this. Hopefully nothing broke.

**Comment by holgerd77** [comment]
No no, everything fine, glad that we have this finally out.

**Pull request merged**
