### PR TITLE
Added verifyPublicKey to verify publicKey, privateKey pair. 

### PR DESCRIPTION
**Pull request by dadepo**

### CODE REVIEW

**Comment by dadepo** [comment]
I am at Devconnect :) and I ran into couple of guys who work on Ethereum-js at a party. Don’t ask me their names, can’t remember :)

**Comment by holgerd77** [comment]
> I am at Devconnect :) and I ran into couple of guys who work on Ethereum-js at a party. Don’t ask me their names, can’t remember :)

Haha, nice 😆, LGTM, will merge.

**Comment by holgerd77** [comment]
Some additional security remark: have also checked the `package-lock.json` additions along review.

**Review by holgerd77 — APPROVED** [review]
LGTM

**Comment by dadepo** [comment]
Thanks for merging. I think this issue #142 can also be closed.

**Pull request merged**
