### PR TITLE
Removing hdkey native dependency

### PR DESCRIPTION
**Pull request by nebojsa94**
This PR removes hdkey dependency and instead uses ethereum-cryptography package that doesn't require native dependency compiling.

### CODE REVIEW

**Comment by cgewecke** [comment]
Leaving some notes as requested...

PR pulls `hdkey` from [js-ethereum-cryptography][1]. 

+ Superficially, the package version is dropping from 2.0.1 to [1.1.2][1]. However, the relevant changes in V2 were written by @alcuadrado and are included in the `ethereum-cryptography` implementation via a [shim][2]
+ Current package and proposed replacement both use the N-API based sepk256k1@4.0.1. (No change)
+ The [API remains the same][3] with additional benefits
  + built-in TypeScript types
  + can be bundled with rollup

It should now be possible to rewrite this line as an `import`

https://github.com/ethereumjs/ethereumjs-wallet/blob/2121d5a32195e595accc9dce81d14bae8b4e6de6/src/hdkey.ts#L3

-----
In sum, this is +/- the same package but aligns the deps here with js-ethereum-cryptography's goal of standardizing the way crypto packages are managed across the eco-system's libraries. 

The only relevant Trail of Bits audit recommendation [has been addressed][4] (though technically the hdkey submodule at j-e-c is not the latest published version.)

LGTM 👍 

[1]: https://github.com/cryptocoinjs/hdkey/tree/42637e381bdef0c8f785b14f5b66a80dad969514
[2]: https://github.com/ethereum/js-ethereum-cryptography/blob/master/src/shims/hdkey-secp256k1v3.ts
[3]: https://github.com/ethereum/js-ethereum-cryptography#hierarchical-deterministic-keys-submodule
[4]: https://github.com/ethereum/js-ethereum-cryptography/blob/master/audit/Changes_after_audit.md#tob-nomic-006-submodule-management

**Comment by holgerd77** [comment]
Thanks for this comprehensive write-up @cgewecke!

@nebojsa94 Can you update the HDKey requires to imports (there is another one in the tests) as suggested by Chris?

I think we are then ready with all the changes (the `ethereumjs-util` update will come in here organically once we are merge-ready and have released there) and can finally do a `v1.0.0` wallet release early/mid next week. 😄

**Comment by nebojsa94** [comment]
@holgerd77 I've updated the HDKey require to import in [hdkey.ts](https://github.com/Tenderly/ethereumjs-wallet/blob/c0edad37c90d63be60b49048b19704c67a6e8655/src/hdkey.ts#L3), I wasn't able to locate the require in tests, can you point the line?

**Comment by alcuadrado** [comment]
Hey @cgewecke ! Thanks for digging into this.

As you mention, the hdkey version is outdated, but the same changes are applied locally. I'm working on getting those incorporated upstream here: https://github.com/cryptocoinjs/hdkey/pull/41

**Pull request merged**
