### PR TITLE
Add typescript types to ethereumjs wallet

### PR DESCRIPTION
**Pull request by HenryNguyen5**
This PR adds typings to the library for external users using TS to use. MyCrypto made them while contributing to https://github.com/MyCryptoHQ/MyCrypto for the team to use internally, and thought it would be a good idea to upstream it so that the community can enjoy static typing too. JS users will see no impact on these typing files since they are only present during static time. TS users will get type safety when using the library, but again, at run-time it will be the exact same behavior with or without types. We made the typing file by cross comparing the documentation against the source code, and it is currently in use in the MyCrypto repo. We would gladly help maintain the typings for this repo from now on if you'd like.

We have typescript typings for ethereumjs-tx too https://github.com/ethereumjs/ethereumjs-tx/pull/88, and am currently preparing types for ethereumjs-util.

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi, thanks for the PR, that is quite some work. I would be happier though, if you discuss stuff like this - especially as a first-time-contributor - in an issue first (or did you directly discuss on some other place?) before introducing new toolchain components or add parts to the technology stack. There is a bigger chance to get rejected with this.

**Comment by axic** [comment]
Can you please point us to some documentation explaining how this works?

The downside is since there are no tests it is really hard to verify this is correct and those making changes to this repo do not really understand Typescript but would be required to keep it in-sync with any other change.

**Comment by HenryNguyen5** [comment]
Hi @holgerd77 @axic, sorry i forgot to include a description as it was getting late when i opened the PR. I can add type tests if you'd like (they look like this https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/angular-agility/angular-agility-tests.ts). They don't validate any of the actual functionality of the library, type tests just make sure the typescript compiler doesn't throw an error on valid inputs to the API

**Comment by holgerd77** [comment]
Hi, just wanted to have a look into this and I installed Visual Studio Code, switched to your branch with the TypeScript files, opened the main folder in the editor and then the ``index.js`` file, but on hovering over the various functions I am not getting any additional type information. Am I doing something wrong?

I am also not getting, that you are defining interfaces with names like ``IPresaleWallet``, which doesn't occur anywhere in the JS code base.

**Comment by krzkaczor** [comment]
My personal opinion would be not to merge this and wait for full typescript rewrite. Chances are that these are not accurate typings and they will make use of this library harder.

**Comment by whymarrh** [comment]
I agree that a TypeScript rewrite would be the best way to generate these typings.

**Pull request closed without merging**
