### PR TITLE
Allow injection of external crypto routines to override those in library

### PR DESCRIPTION
**Pull request by paullinator**
On other platforms such as React Native, standard crypto routines and other system libraries may not be available. It would be beneficial to allow such routines to be injected into ethereum-js wallet for use on such platforms. This change allows such an injection. For now only randomBytes is supported but this can be extended to other crypto functions.

### CODE REVIEW

**Comment by axic** [comment]
Sorry for the very delayed response. Babel or browserify should be able to inject `crypto-browserify` which gives a browser based implementation for these. You could also check out https://github.com/ethereumjs/browser-builds for browser compatible builds.

Does that solve your problem?

**Comment by paullinator** [comment]
browserify does not solve the problem. On React Native, JS code runs very slow as it's not running with JIT. Also, browser functions are also not available. RN is it's own JS environment different from either Node or browser. This change is needed to allow override of platform specific routines.

**Comment by axic** [comment]
@paullinator Can you please try #63 (The rest of the use cases of `crypto` will be removed there too)? I think that is the real solution.

**Comment by axic** [comment]
If that PR does't solve your issue than React Native support should be added to upstream https://github.com/crypto-browserify/randombytes.

**Comment by paullinator** [comment]
`randombytes` is not a package available in react-native and it cannot be implemented as such. RN doesn't have a random number generator that is synchronous, so random bytes needs to be initialized first with a call to native C++ code. Then future calls can do a SHA256 hash of the random value from native code. The way this is implemented in ethereumjs-wallet assumes one can make a synchronous call to randombytes which can't happen in RN. An injection is really the best way and it can at least be optional.

**Comment by paullinator** [comment]
This can't be added upstream as the code here still assumes an asynchronous call into a library with no chance to initialize the library.

**Comment by axic** [comment]
I wasn't aware it was async in React Native, quickly glimpsed at the wrappers which use `NativeModules.RNRandomBytes`.

However, there are only 3 places where `randomBytes` is used: `generate`, `generateVanityAddress` and `toV3`.

Since `toV3` offers the option to specify all the randomly generated fields at invocation (`salt`, `iv`, `uuid`) I would assume that can live without this change.

However, `generate` of course offers no option currently. How about extending `generate*` with and optional `opts` parameter, in which it would accept a `randomBytes` function?

**Comment by paullinator** [comment]
That would work in this one use case but if we ever wanted to use other crypto routines, they may not work. 

It would be a better best practice to accept injections for platform specific routines like crypto, disk, and network. 

As an aside, due to RN not being able to do Native code synchronously, one of the biggest hurdles is making the code async compatible. I’d suggest keeping any disk, network, or crypto routines async even if they don’t have to be. Just wrap them in an async function.

**Pull request closed without merging**
