### PR TITLE
Change scrypt.js to scrypt-shim

### PR DESCRIPTION
**Pull request by dmihal**
scrypt.js depends on scrypt, which is not maintained and breaks on Node 12.

I've changed to the @web3-js/scrypt-shim package, which is used by Web3.js

### CODE REVIEW

**Comment by kumavis** [comment]
`npm run lint` failed

**Comment by dmihal** [comment]
@kumavis fixed!

**Comment by holgerd77** [comment]
Would like to get a thirdparty opinion, @cgewecke could you give an assessment if you see this as a valid and side-effects-free replacement?

**Comment by kumavis** [comment]
`scrypt` is blocking node v12 support
node v10 is about to transition from "active LTS" to "maintenance"

**Comment by cgewecke** [comment]
@holger As far as I can see, this is a valid replacement. There's a documented issue running out of memory in some cases where `n` is a large value - the shim handles this case with a warning and falls back on scryptsy. No one has reported any problems / weird behavior with the package in the last 6 - 8 months.

@michaelsbradleyjr put all this together and has done a lot of research into its details. 

@dmihal @kumavis After looking through the threads below, is it safe to assume you're still comfortable with this change? 

+ [web3: introduce fallback when Node's built-in scrypt experiences memory exhaustion][1]
+ [web3: golang's (e.g geth's) scrypt isn't compliant with the RFC for scrypt whlie Node's is][2]

wrt the second item, @michaelsbradleyjr wrote:

> if someone using Node wanted to be able to process the exact same set of scrypt parameters that's possible with golang (e.g. with geth) then they'd either need to use a non-compliant pure JS implementation or the old scrypt package (and in the latter case they'd need to be using Node <= 12.0.0).

[1]: https://github.com/ethereum/web3.js/pull/2952 
[2]:  https://github.com/ethereum/web3.js/issues/3284#issuecomment-568105184

**Comment by kumavis** [comment]
this could also be solved at the `scrypt.js` level, with help from @axic 
https://github.com/axic/scrypt.js/pull/8

**Comment by kumavis** [comment]
@cgewecke @michaelsbradleyjr thanks for the excellent research :tada: 
If there is strong need for the RFC-noncompliant parameters, we could check them and then fallback to the js implementation. That way you get the performance boost in the majority of cases.

That said, I think its fine if we don't support the RFC-noncompliant parameters, barring evidence that they are commonly used somewhere. but respect semver and publish behind a major

**Comment by kumavis** [comment]
thanks @holgerd77 
anything blocking the next release?

**Comment by holgerd77** [comment]
There needs to be some update work done on the docs during the next days https://github.com/ethereumjs/ethereumjs-wallet/pull/98, then we are ready to go.

**Comment by holgerd77** [comment]
Hi, some update here: we had a longer discussion on this on our last team call and there was a larger agreement that we would generally want to move away here from a native implementation and instead use a pure JS library.

So we would like to do another update here. We are currently targeting to use the [scrypt.js](https://github.com/ricmoo/scrypt-js) implementation a) @ricmoo is also working in the EF JS team, so ways are short and b) library is async and we can move to expose some parts of the API as async functionality.

@ryanio has opened an according PR here: https://github.com/ethereumjs/ethereumjs-wallet/pull/125

Wanted to first ask everyone involved in the discussion here, can you also live with this solution? Any feedback - both positive and negative - is highly appreciated! 😄

//cc @evertonfraga

**Comment by holgerd77** [comment]
Will also //cc to @michaelsbradleyjr

**Comment by holgerd77** [comment]
Short update on the `scrypt-js` switch: I would want to merge this relatively quickly since the `v1.0.0` release is already delayed for so long. I will give this another 24 hour response period here and then merge if no further comments or questions arise.

**Pull request merged**
