### PR TITLE
Switched to babel ES5 build in dist folder for package distribution

### PR DESCRIPTION
**Pull request by holgerd77**
Since topic also came up here:

This PR switches to babelified ``ES5`` packaging. Tests are included in the babel build. For test run with the ``test`` script, distribution tests are used, ``coverage`` is using the original test files in the ``test`` folder.

### CODE REVIEW

**Comment by holgerd77** [comment]
Dist folder is only created for the build, otherwise there is the risk if inconsistent repository states.

**Comment by mohammadrafigh** [comment]
ok but this way npm won't fetch and build the dist folder when using `npm install ethereumjs-wallet` in another project. or maybe you want to publish dists separately?

**Comment by holgerd77** [comment]
I have just tested this for another library (``ethereumjs-util``) to double-check, ``dist`` folder is actually included there when library is installed with npm.

The ``dist`` folder is included with the ``files`` directive in ``package.json``, so it is distributed with the npm package, npm is ignoring .gitignore here. Do you have any other information beyond that I didn't consider here?

**Comment by mohammadrafigh** [comment]
I also use `ethereumjs-util` and it's ok, in my node_modules there is a dist folder. but there is no dist folder in `ethereumjs-wallet` when fetching from github using npm. maybe there is a bug in npm that won't run build script for dependencies fetched from git. so if this is the case then yes this PR is ok IMO. thanks for your fast PR.

**Pull request merged**
